"use client";

import { FormEvent, useMemo, useState } from "react";
import { Banknote, Ban, CreditCard, Search, ShoppingBag } from "lucide-react";
import PosNav from "./PosNav";

type Sale = { id: number; receipt_number: string; order_type: string; payment_method: string; payment_status: string; subtotal: number; discount_amount: number; total: number; status: string; created_at: string; voided_at: string | null; void_reason: string | null; profiles: { full_name: string | null } | null; order_items: { name: string; quantity: number; line_total: number }[] };
const peso = (v: number) => `₱${Number(v).toLocaleString("en-PH", { minimumFractionDigits: 2 })}`;

export default function SalesHistory({ cashierName, isAdmin, initialSales }: { cashierName: string; isAdmin: boolean; initialSales: Sale[] }) {
  const [sales, setSales] = useState(initialSales); const [search, setSearch] = useState(""); const [voiding, setVoiding] = useState<Sale | null>(null); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  const valid = sales.filter(s => !s.voided_at); const today = new Date().toDateString(); const todaySales = valid.filter(s => new Date(s.created_at).toDateString() === today);
  const totals = useMemo(() => ({ revenue: todaySales.reduce((a, s) => a + Number(s.total), 0), transactions: todaySales.length, cash: todaySales.filter(s => s.payment_method === "cash").reduce((a, s) => a + Number(s.total), 0), digital: todaySales.filter(s => s.payment_method !== "cash").reduce((a, s) => a + Number(s.total), 0) }), [todaySales]);
  const shown = sales.filter(s => `${s.receipt_number} ${s.id} ${s.payment_method}`.toLowerCase().includes(search.toLowerCase()));
  async function voidSale(e: FormEvent<HTMLFormElement>) { e.preventDefault(); if (!voiding) return; const reason = String(new FormData(e.currentTarget).get("reason") || ""); setBusy(true); setMessage(""); const response = await fetch("/api/pos/sales/void", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ orderId: voiding.id, reason }) }); const result = await response.json(); setBusy(false); if (!response.ok) return setMessage(result.error || "Could not void sale."); setSales(current => current.map(s => s.id === voiding.id ? { ...s, voided_at: new Date().toISOString(), void_reason: reason, status: "cancelled", payment_status: "refunded" } : s)); setVoiding(null); setMessage(`Sale ${voiding.receipt_number} was voided and its stock was restored.`); }
  return <main className="min-h-screen bg-[#F2EDE4] text-[#3B2716]">
    <header className="flex flex-wrap items-center justify-between gap-3 bg-[#2F4530] px-4 py-3 text-white md:px-8"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-[#D7A24A]">Kainan sa Tabing Lawa</p><h1 className="text-2xl font-semibold">Sales</h1></div><PosNav active="sales"/><p className="text-sm text-white/70">{cashierName}</p></header>
    <div className="mx-auto max-w-7xl space-y-6 p-4 md:p-8">
      <section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Card label="Today's net sales" value={peso(totals.revenue)} icon={<ShoppingBag/>}/><Card label="Transactions" value={String(totals.transactions)} icon={<CreditCard/>}/><Card label="Cash" value={peso(totals.cash)} icon={<Banknote/>}/><Card label="GCash & card" value={peso(totals.digital)} icon={<CreditCard/>}/></section>
      {message && <p className={`rounded-xl p-3 text-sm ${message.includes("was voided") ? "bg-emerald-50 text-emerald-700" : "bg-red-50 text-red-700"}`}>{message}</p>}
      <section className="rounded-2xl border border-[#DED2BF] bg-white p-4 md:p-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-2xl font-semibold">Last 30 days</h2><p className="text-sm text-[#74685C]">Paid, refunded, and voided counter transactions.</p></div><label className="relative"><Search className="absolute left-3 top-3 text-[#8B8175]" size={18}/><input value={search} onChange={e => setSearch(e.target.value)} placeholder="Receipt or payment" className="rounded-xl border border-[#DED2BF] py-2.5 pl-10 pr-3 outline-none"/></label></div>
        <div className="mt-5 space-y-3">{shown.map(sale => <article key={sale.id} className={`rounded-xl border p-4 ${sale.voided_at ? "border-red-200 bg-red-50/50" : "border-[#E4D6C0]"}`}><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex flex-wrap items-center gap-2"><b>{sale.receipt_number}</b><span className="rounded-full bg-[#F1E8D9] px-2 py-1 text-xs font-bold uppercase">{sale.payment_method}</span>{sale.voided_at && <span className="rounded-full bg-red-100 px-2 py-1 text-xs font-bold text-red-700">VOIDED</span>}</div><p className="mt-1 text-xs text-[#74685C]">{new Date(sale.created_at).toLocaleString("en-PH")} · {sale.profiles?.full_name || "Staff"} · {sale.order_type.replace("_", " ")}</p></div><div className="text-right"><p className={`text-xl font-bold ${sale.voided_at ? "line-through text-red-500" : ""}`}>{peso(sale.total)}</p>{Number(sale.discount_amount) > 0 && <small className="text-emerald-700">Discount {peso(sale.discount_amount)}</small>}</div></div><details className="mt-3"><summary className="cursor-pointer text-sm font-bold text-[#2F4530]">View {sale.order_items.length} line item(s)</summary><div className="mt-2 space-y-1 text-sm">{sale.order_items.map((item, i) => <p key={i} className="flex justify-between"><span>{item.quantity}× {item.name}</span><span>{peso(item.line_total)}</span></p>)}</div></details><div className="mt-3 flex items-end justify-between gap-3">{sale.voided_at ? <p className="text-xs text-red-700">Reason: {sale.void_reason}</p> : <span/>}{isAdmin && !sale.voided_at && <button onClick={() => { setVoiding(sale); setMessage(""); }} className="flex items-center gap-2 rounded-lg border border-red-200 px-3 py-2 text-xs font-bold text-red-700"><Ban size={15}/> Void & restore stock</button>}</div></article>)}</div>
      </section>
    </div>
    {voiding && <div className="fixed inset-0 z-50 grid place-items-center bg-black/50 p-4"><form onSubmit={voidSale} className="w-full max-w-md rounded-2xl bg-white p-6 shadow-2xl"><h2 className="text-2xl font-semibold">Void {voiding.receipt_number}?</h2><p className="mt-2 text-sm text-[#74685C]">This refunds the transaction in the ledger and returns all recipe ingredients to stock.</p><textarea name="reason" required rows={3} placeholder="Required reason" className="mt-4 w-full rounded-xl border border-[#DED2BF] p-3 outline-none"/>{message && <p className="mt-2 text-sm text-red-700">{message}</p>}<div className="mt-4 grid grid-cols-2 gap-2"><button type="button" onClick={() => setVoiding(null)} className="rounded-xl bg-[#EFE8DD] p-3 font-bold">Cancel</button><button disabled={busy} className="rounded-xl bg-red-700 p-3 font-bold text-white disabled:opacity-50">{busy ? "Voiding…" : "Confirm void"}</button></div></form></div>}
  </main>;
}
function Card({ label, value, icon }: { label: string; value: string; icon: React.ReactNode }) { return <div className="rounded-2xl border border-[#DED2BF] bg-white p-5"><div className="flex items-center justify-between text-[#8B8175]"><p className="text-xs font-bold uppercase tracking-wider">{label}</p>{icon}</div><p className="mt-3 text-3xl font-semibold">{value}</p></div>; }
