-- Cached daily AI review insights and demand forecasts for restaurant admins.
create table if not exists public.admin_ai_insights (
  id bigint generated by default as identity primary key,
  insight_date date not null unique,
  content jsonb not null,
  stats_snapshot jsonb not null,
  model text not null,
  generated_at timestamptz not null default now(),
  generated_by uuid references auth.users(id) on delete set null
);

alter table public.admin_ai_insights enable row level security;

drop policy if exists "Admins can view AI insights" on public.admin_ai_insights;
create policy "Admins can view AI insights" on public.admin_ai_insights
for select to authenticated using ((select public.is_admin()));

drop policy if exists "Admins can create AI insights" on public.admin_ai_insights;
create policy "Admins can create AI insights" on public.admin_ai_insights
for insert to authenticated
with check ((select public.is_admin()) and generated_by = (select auth.uid()));

drop policy if exists "Admins can update AI insights" on public.admin_ai_insights;
create policy "Admins can update AI insights" on public.admin_ai_insights
for update to authenticated using ((select public.is_admin()))
with check ((select public.is_admin()) and generated_by = (select auth.uid()));

comment on table public.admin_ai_insights is
  'One cached review-insight and seven-day demand forecast per Manila calendar day.';
