create extension if not exists pgcrypto;

alter table public.profiles
  add column if not exists loyalty_code uuid not null default gen_random_uuid();

create unique index if not exists profiles_loyalty_code_key
  on public.profiles (loyalty_code);

create table if not exists public.loyalty_visits (
  id bigint generated by default as identity primary key,
  customer_id uuid not null references public.profiles(id) on delete cascade,
  recorded_by uuid not null references public.profiles(id),
  visit_type text not null default 'walk_in' check (visit_type in ('walk_in', 'reservation')),
  reservation_id bigint references public.reservations(id),
  receipt_reference text,
  cycle_visit_number smallint not null check (cycle_visit_number between 1 and 5),
  reward_applied boolean not null default false,
  eligible_amount numeric(12,2),
  discount_amount numeric(12,2) not null default 0,
  created_at timestamptz not null default now()
);

create unique index if not exists loyalty_visits_receipt_reference_key
  on public.loyalty_visits (lower(receipt_reference))
  where receipt_reference is not null;

create unique index if not exists loyalty_visits_reservation_id_key
  on public.loyalty_visits (reservation_id)
  where reservation_id is not null;

alter table public.loyalty_visits enable row level security;

create policy "Customers can view their loyalty visits"
on public.loyalty_visits for select to authenticated
using ((select auth.uid()) = customer_id);

create policy "Admins can view loyalty visits"
on public.loyalty_visits for select to authenticated
using (exists (
  select 1 from public.profiles
  where profiles.id = (select auth.uid()) and profiles.role = 'admin'
));

create or replace function public.get_loyalty_customer(scan_code uuid)
returns table (
  customer_id uuid,
  full_name text,
  completed_visits bigint,
  next_visit_number integer,
  reward_due boolean
)
language plpgsql
security definer
set search_path = public
as $$
declare
  is_admin boolean;
begin
  select exists (
    select 1 from public.profiles p
    where p.id = auth.uid() and p.role = 'admin'
  ) into is_admin;
  if not is_admin then raise exception 'Admin access required'; end if;

  return query
  select p.id, p.full_name, count(v.id),
    ((count(v.id) % 5) + 1)::integer,
    ((count(v.id) % 5) + 1) = 5
  from public.profiles p
  left join public.loyalty_visits v on v.customer_id = p.id
  where p.loyalty_code = scan_code and p.role = 'customer'
  group by p.id, p.full_name;
end;
$$;

create or replace function public.record_loyalty_visit(
  scan_code uuid,
  receipt text,
  bill_amount numeric default null,
  reservation_ref bigint default null
)
returns table (
  visit_id bigint,
  cycle_visit_number integer,
  reward_applied boolean,
  discount_amount numeric,
  next_visit_number integer
)
language plpgsql
security definer
set search_path = public
as $$
declare
  customer uuid;
  visit_count bigint;
  visit_number integer;
  new_visit_id bigint;
  discount numeric(12,2) := 0;
begin
  if not exists (select 1 from public.profiles where id = auth.uid() and role = 'admin') then
    raise exception 'Admin access required';
  end if;
  if nullif(trim(receipt), '') is null then raise exception 'Receipt reference is required'; end if;

  select id into customer from public.profiles
  where loyalty_code = scan_code and role = 'customer' for update;
  if customer is null then raise exception 'Loyalty QR was not found'; end if;

  if reservation_ref is not null and not exists (
    select 1 from public.reservations
    where id = reservation_ref and user_id = customer and status = 'completed'
  ) then
    raise exception 'Reservation must belong to this customer and be marked completed';
  end if;

  select count(*) into visit_count from public.loyalty_visits where customer_id = customer;
  visit_number := (visit_count % 5) + 1;
  if visit_number = 5 then
    if bill_amount is null or bill_amount <= 0 then raise exception 'Eligible bill amount is required for the fifth visit'; end if;
    discount := round(bill_amount * 0.10, 2);
  end if;

  insert into public.loyalty_visits (
    customer_id, recorded_by, visit_type, reservation_id, receipt_reference, cycle_visit_number,
    reward_applied, eligible_amount, discount_amount
  ) values (
    customer, auth.uid(), case when reservation_ref is null then 'walk_in' else 'reservation' end,
    reservation_ref, trim(receipt), visit_number,
    visit_number = 5, case when visit_number = 5 then bill_amount else null end, discount
  ) returning id into new_visit_id;

  return query select new_visit_id, visit_number, visit_number = 5, discount,
    ((visit_number % 5) + 1)::integer;
end;
$$;

grant execute on function public.get_loyalty_customer(uuid) to authenticated;
grant execute on function public.record_loyalty_visit(uuid, text, numeric, bigint) to authenticated;
