-- Complete POS inventory, recipe costing, stock ledger, and controlled voids.
create table if not exists public.inventory_items (
  id bigint generated by default as identity primary key,
  name text not null unique,
  sku text unique,
  unit text not null default 'piece',
  quantity numeric(14,3) not null default 0,
  reorder_level numeric(14,3) not null default 0,
  unit_cost numeric(12,2) not null default 0,
  supplier text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint inventory_nonnegative check (quantity >= 0 and reorder_level >= 0 and unit_cost >= 0)
);

create table if not exists public.menu_item_ingredients (
  menu_item_id bigint not null references public.menu_items(id) on delete cascade,
  inventory_item_id bigint not null references public.inventory_items(id) on delete cascade,
  quantity_required numeric(14,3) not null check (quantity_required > 0),
  primary key (menu_item_id, inventory_item_id)
);

create table if not exists public.inventory_movements (
  id bigint generated by default as identity primary key,
  inventory_item_id bigint not null references public.inventory_items(id),
  movement_type text not null check (movement_type in ('opening', 'purchase', 'sale', 'waste', 'adjustment', 'void')),
  quantity_change numeric(14,3) not null check (quantity_change <> 0),
  quantity_after numeric(14,3) not null,
  reason text,
  order_id bigint references public.orders(id),
  recorded_by uuid references public.profiles(id),
  created_at timestamptz not null default now()
);

alter table public.orders
  add column if not exists voided_at timestamptz,
  add column if not exists voided_by uuid references public.profiles(id),
  add column if not exists void_reason text;

create index if not exists inventory_movements_item_created_idx on public.inventory_movements (inventory_item_id, created_at desc);
create index if not exists inventory_movements_order_idx on public.inventory_movements (order_id) where order_id is not null;
create index if not exists orders_pos_created_idx on public.orders (created_at desc) where order_source = 'pos';

alter table public.inventory_items enable row level security;
alter table public.menu_item_ingredients enable row level security;
alter table public.inventory_movements enable row level security;

drop policy if exists "Staff can view inventory" on public.inventory_items;
create policy "Staff can view inventory" on public.inventory_items for select to authenticated using (public.is_staff());
drop policy if exists "Admins can manage inventory" on public.inventory_items;
create policy "Admins can manage inventory" on public.inventory_items for all to authenticated
  using (exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin'))
  with check (exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin'));
drop policy if exists "Staff can view recipes" on public.menu_item_ingredients;
create policy "Staff can view recipes" on public.menu_item_ingredients for select to authenticated using (public.is_staff());
drop policy if exists "Admins can manage recipes" on public.menu_item_ingredients;
create policy "Admins can manage recipes" on public.menu_item_ingredients for all to authenticated
  using (exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin'))
  with check (exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin'));
drop policy if exists "Staff can view stock ledger" on public.inventory_movements;
create policy "Staff can view stock ledger" on public.inventory_movements for select to authenticated using (public.is_staff());

grant select on public.inventory_items, public.menu_item_ingredients, public.inventory_movements to authenticated;
grant insert, update, delete on public.inventory_items, public.menu_item_ingredients to authenticated;
grant usage, select on sequence public.inventory_items_id_seq to authenticated;

create or replace function public.adjust_inventory(
  stock_item_id bigint, quantity_delta numeric, movement_kind text, movement_reason text default null
) returns public.inventory_items
language plpgsql security definer set search_path = public as $$
declare updated_item public.inventory_items;
begin
  if not public.is_staff() then raise exception 'Staff access required'; end if;
  if movement_kind not in ('opening', 'purchase', 'waste', 'adjustment') then raise exception 'Invalid stock movement'; end if;
  if quantity_delta = 0 then raise exception 'Quantity change cannot be zero'; end if;
  update public.inventory_items set quantity = quantity + quantity_delta, updated_at = now()
    where id = stock_item_id and quantity + quantity_delta >= 0 returning * into updated_item;
  if updated_item.id is null then raise exception 'Stock item not found or quantity would become negative'; end if;
  insert into public.inventory_movements (inventory_item_id, movement_type, quantity_change, quantity_after, reason, recorded_by)
    values (stock_item_id, movement_kind, quantity_delta, updated_item.quantity, nullif(trim(movement_reason), ''), auth.uid());
  return updated_item;
end; $$;
grant execute on function public.adjust_inventory(bigint, numeric, text, text) to authenticated;

create or replace function public.consume_pos_inventory()
returns trigger language plpgsql security definer set search_path = public as $$
declare recipe record; stock public.inventory_items; needed numeric(14,3); source text;
begin
  select order_source into source from public.orders where id = new.order_id;
  if source <> 'pos' then return new; end if;
  for recipe in select * from public.menu_item_ingredients where menu_item_id = new.menu_item_id loop
    needed := recipe.quantity_required * new.quantity;
    select * into stock from public.inventory_items where id = recipe.inventory_item_id and is_active for update;
    if stock.id is null then raise exception 'A recipe ingredient is inactive or missing'; end if;
    if stock.quantity < needed then raise exception 'Insufficient stock for % (available: % %)', stock.name, stock.quantity, stock.unit; end if;
    update public.inventory_items set quantity = quantity - needed, updated_at = now() where id = stock.id returning * into stock;
    insert into public.inventory_movements (inventory_item_id, movement_type, quantity_change, quantity_after, reason, order_id, recorded_by)
      values (stock.id, 'sale', -needed, stock.quantity, 'POS sale', new.order_id, auth.uid());
  end loop;
  return new;
end; $$;

drop trigger if exists consume_pos_inventory_on_order_item on public.order_items;
create trigger consume_pos_inventory_on_order_item after insert on public.order_items
  for each row execute function public.consume_pos_inventory();

create or replace function public.void_pos_sale(pos_order_id bigint, reason_text text)
returns jsonb language plpgsql security definer set search_path = public as $$
declare sale public.orders; movement record; stock public.inventory_items;
begin
  if not exists (select 1 from public.profiles where id = auth.uid() and role = 'admin') then raise exception 'Admin access required'; end if;
  select * into sale from public.orders where id = pos_order_id and order_source = 'pos' for update;
  if sale.id is null then raise exception 'POS sale not found'; end if;
  if sale.voided_at is not null then raise exception 'Sale is already voided'; end if;
  if nullif(trim(reason_text), '') is null then raise exception 'A void reason is required'; end if;
  for movement in select * from public.inventory_movements where order_id = pos_order_id and movement_type = 'sale' order by id loop
    update public.inventory_items set quantity = quantity + abs(movement.quantity_change), updated_at = now()
      where id = movement.inventory_item_id returning * into stock;
    insert into public.inventory_movements (inventory_item_id, movement_type, quantity_change, quantity_after, reason, order_id, recorded_by)
      values (movement.inventory_item_id, 'void', abs(movement.quantity_change), stock.quantity, 'Voided sale: ' || trim(reason_text), pos_order_id, auth.uid());
  end loop;
  update public.orders set status = 'cancelled', payment_status = 'refunded', voided_at = now(), voided_by = auth.uid(), void_reason = trim(reason_text)
    where id = pos_order_id;
  return jsonb_build_object('order_id', pos_order_id, 'voided', true);
end; $$;
grant execute on function public.void_pos_sale(bigint, text) to authenticated;
