create table if not exists public.admin_daily_briefings (
  id bigint generated by default as identity primary key,
  briefing_date date not null unique,
  content jsonb not null,
  stats_snapshot jsonb not null,
  model text not null,
  generated_at timestamptz not null default now(),
  generated_by uuid references auth.users(id) on delete set null
);

alter table public.admin_daily_briefings enable row level security;

create policy "Admins can view daily briefings" on public.admin_daily_briefings
for select to authenticated using ((select public.is_admin()));

create policy "Admins can create daily briefings" on public.admin_daily_briefings
for insert to authenticated
with check ((select public.is_admin()) and generated_by = (select auth.uid()));

create policy "Admins can update daily briefings" on public.admin_daily_briefings
for update to authenticated using ((select public.is_admin()))
with check ((select public.is_admin()) and generated_by = (select auth.uid()));

comment on table public.admin_daily_briefings is
  'One cached, staff-facing AI operations briefing per Manila calendar day.';
